version: "3.7"
services:
  database:
    container_name: "postgres_jp"
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8000:8000"
    restart: always

